### ISSUE TITLE
Unexpected anonymous System.register call

### ISSUE THREAD

**Issue by monobyte** [cmichaelgraham/skeleton-navigation-typescript-vscode#3]
I've followed the readme, but when I run the app I just see the loading spinner and an error in console.

shim.min.js:1773 Error: Unexpected anonymous System.register call.(…)

Any ideas? I'm running on a mac with Node v5.1.1

**Comment by Aniel** [comment]
try removing in your `tsconfig.json` the `module` option. See: https://github.com/microsoft/TypeScript/issues/5960#issuecomment-162627574

**Comment by monobyte** [comment]
That fixed it! Thanks
